---
title: "ingarch_analysis"
author: "Alexander Schwaiger"
date: "2022-12-20"
output: pdf_document
---

```{r eval=FALSE, message=FALSE, warning=FALSE}
source("General_Dependency.R")
source("Coda_Function.R") 
source("Ingarch_Function.R")
source("General_Function.R")
source("General_PlotFunctions.R")
```


Plot parameters 
```{r eval = FALSE}
text_size <- 50
save_plots <- T
```


Preparation
```{r eval = FALSE}

#Choosing only fridges with all 4 categories
help1 <- weekly_category_data%>%
  group_by(fridge_id)%>%
  dplyr::select(main_category_id)%>%
  unique()%>%
  count(fridge_id)
  
ids_all <- help1$fridge_id[help1$n ==4]

ids <- ids_all

if(all(ids == ids_all)){
  ids_save <- "_all_"
}else {
  ids_save <- paste(ids,collapse = "-")
}

frame <- 0.5
window_method <- "extending"
save_results <- F
HistoryLength <- 1
zero_handling_ingarch <- "none"

#Ingarch specifications
MainCat <- 2

```


```{r eval=FALSE, include=FALSE}
ingarch_result <-
  Ingarch.Analysis(
    Data_Raw= weekly_category_data,
    Id = 10,
    Frame = frame,
    Distribution = "nbinom",
    Category_Main = c("1","2","3","4"),
    WindowMethod = "overlapping",
    ZeroHandling = "none",
    External = F,
    Multicore = F,
    NCores = 10,
    PastOb = 1,
    PastMean = 1,
    HistoryLength = HistoryLength,
    TakeSubCategory = F
  )
  
  if(save_results){
  save(ingarch_result,file=here("Code/results",paste("ingarch_result_ids",paste(ids_save,collapse="-"),
                                             "_win_lgth",gsub("[.]","",frame),"_history_lght",gsub("[.]","",HistoryLength),
                                             "zero_handling_",zero_handling_ingarch,".RData",sep="")))

}
```


Loading previous results
```{r}
ids <- unique(ingarch_result$result$id)
PredictionStep <- 1
frame <- unique(ingarch_result$result$frame)
window_method <- unique(ingarch_result$result$windowMethod)
save_results <- F
HistoryLength <- unique(ingarch_result$result$history)

#Ingarch specifications
distr<-unique(ingarch_result$result$distribution)
zero_handling_ingarch <- unique(ingarch_result$result$zeroHandling)
external <- unique(ingarch_result$result$external)
if(external){
  external_plot <-"with external factors"
}else external_plot <- ""
past_means <- unique(ingarch_result$result$pastMean)
past_obs <- unique(ingarch_result$result$pastOb)
ingarch_settings <- expand_grid(past_means,past_obs)
MainCat <- unique(ingarch_result$result$main_category)
```


Error measure calculations
```{r}
Category <- as.numeric(unique(ingarch_result$result$category))

ingarch_model_error <- Model.Error(ingarch_result$result,Fnct = "Mse",Category = Category ) %>% 
                       Model.ErrorOverall(Fnct = "sum",SplitByGroup = F,Category = Category )

ingarch_model_error_split <- Model.Error(ingarch_result$result,Fnct = "Mse",Category =Category ) %>% 
                             Model.ErrorOverall(Fnct = "sum",SplitByGroup = T,Groups = as.list(Category))
```


Error Boxplot by category
```{r}
psbs<-ggplot(ingarch_model_error_split,aes(x=model,y=error))+
  facet_wrap(vars(group),ncol=length(unique(ingarch_model_error_split$group)),scales = "fixed")+
  geom_boxplot()+
  scale_y_continuous(limits=c(0,5))+
  geom_hline(yintercept =1,linewidth=2)+
  theme(text = element_text(size = text_size),axis.text.x = element_text(size=30))+
  ggtitle(paste("Error measures",sep=" "),subtitle = paste("Window length:",frame, "History:",HistoryLength,",Zero handling",zero_handling_ingarch,sep=" "))

if(save_plots){
  ggsave(filename = here("Plots",paste("Both_ErrorMeasure_combined",ids_save,"_histlgth",HistoryLength,"_win_lgth",frame,"zero_handling_",zero_handling_ingarch,".png",sep="")),plot=psbs,height = 15,width = 20)
}
```


Split Quantile Plot
```{r}
length <- ingarch_result$result %>% group_by(id) %>% dplyr::summarise(n=unique(window_baseLength))

TimeSeries_Length <- data.frame(id = unique(ingarch_result$result$id),
                                length = length$n/
                                  (as.numeric(unique(ingarch_result$result$frame))*as.numeric(unique(ingarch_result$result$history))))
```

```{r}
my_color_methods <- setNames(c("blue"),
                     c("ingarch"))

IngarchError_Sorted_split <- ingarch_model_error_split%>%group_by(group)%>%arrange(.,error)
IngarchQuantiles_split  <- quantile(IngarchError_Sorted_split $error,na.rm = T)

IngarchError_Sorted_split$index <- rep()

for(group_runvar in IngarchError_Sorted_split$group){
  IngarchError_Sorted_split$index[IngarchError_Sorted_split$group==group_runvar] <- seq(1:length(IngarchError_Sorted_split$index[IngarchError_Sorted_split$group==group_runvar]))
}


IngarchError_Sorted_split <- full_join(IngarchError_Sorted_split,TimeSeries_Length,bye ="id")

Quantiles_Index_split  <- data.frame(quant_ind=round(quantile(1:length(unique(IngarchError_Sorted_split$id)))))


Error_Sorted_split <- IngarchError_Sorted_split
Error_Sorted_split$group <- as.factor(Error_Sorted_split$group)

plot_quant_split <- ggplot(Error_Sorted_split ,aes(x=index,y=error,colour=model,size=length))+
  facet_wrap(vars(group),nrow=round(length(unique(IngarchError_Sorted_split$group))/2),scales = "free")+
  geom_point()+
  scale_y_continuous(limits=c(0,5))+
  geom_hline(yintercept=1,linewidth=2)+
# geom_point(data = CodaError_Sorted_split,aes(x=index,y=error,colour=model),size=3)+
  geom_vline(aes(xintercept=quant_ind),data=Quantiles_Index_split)+
  theme(text = element_text(size = text_size))+
  scale_colour_manual("Legend", values = c(my_color_methods),aesthetics = "colour")+
  ggtitle(paste("Error measures sorted",sep=" "),subtitle = paste("Window length:",frame,"History:",HistoryLength,",Zero handling",zero_handling_ingarch,sep=" "))

if(save_plots){
  ggsave(filename = here("Plots",paste("Quantile_Plot_Split",ids_save,"_histlgth",HistoryLength,"win_lgth",frame,"zero_handling_",zero_handling_ingarch,".png",sep="")),
         plot=plot_quant_split,height = 15,width = 20)
}
```


Quantile Plot
```{r}
my_color_methods <- setNames(c("blue"),
                     c("ingarch"))

IngarchError_Sorted <- ingarch_model_error %>% filter(model=="ingarch")%>%arrange(.,error)
IngarchQuantiles <- quantile(IngarchError_Sorted$error,na.rm = T)
IngarchError_Sorted$index <- seq(1:dim(IngarchError_Sorted)[1])
IngarchError_Sorted <- full_join(IngarchError_Sorted,TimeSeries_Length,bye ="id")

Quantiles_Index <- data.frame(quant_ind=findInterval(IngarchQuantiles,IngarchError_Sorted$error))

plot_quant <- ggplot(IngarchError_Sorted,aes(x=index,y=error,colour=model,size=length))+
  geom_point()+
  scale_y_continuous(limits=c(0,5))+
# geom_point(data = CodaError_Sorted,aes(x=index,y=error,colour=model,size=length))+
  geom_hline(yintercept=1,linewidth=2)+
  geom_vline(aes(xintercept=quant_ind),data=Quantiles_Index)+
  theme(text = element_text(size = text_size))+
  scale_colour_manual("Legend", values = c(my_color_methods),aesthetics = "colour")+
  ggtitle(paste("Error measures sorted",sep=" "),subtitle = paste("Window length:",frame, "History:",HistoryLength,",Zero handling",zero_handling_ingarch,sep=" "))

if(save_plots){
  ggsave(filename = here("Plots",paste("Quantile_Plot",ids_save,"_histlgth",HistoryLength,"win_lgth",frame,"zero_handling_",zero_handling_ingarch,".png",sep="")),
         plot=plot_quant,height = 15,width = 20)
}
```


```{r}
FID=10

plot_data_ingarch <- ingarch_result$result%>%filter(id==FID)

data_raw <- weekly_category_data %>%
          filter(fridge_id == FID&
                   main_category_id %in% unique(ingarch_result$result$category)) %>%
          dplyr::select(week_date, main_category_id, sub_category_id, sold) %>%
          Data.Preparation(Category = unique(ingarch_result$result$category),TakeSubCategory = F) %>% 
          pivot_longer(cols=unique(ingarch_result$result$category),names_to="category",values_to="valueTrue")
names(data_raw)[1] <- c("date")


p<-ggplot(plot_data_ingarch,aes(x=date,y=valuePredict),col="blue")+
  facet_wrap(vars(category),ncol=1,scales = "free")+
  geom_point(size=1)+
  geom_ribbon(aes(x=date,y=valuePredict,ymin=lowerBound,ymax=upperBound),
              data=plot_data_ingarch,inherit.aes = F,fill="grey90",linetype="dashed",col="blue")+
  geom_line(data=plot_data_ingarch,
            aes(x=date,y=valuePredict),col="blue")+
  geom_line(data=data_raw,aes(x=date,y=valueTrue),col="black",inherit.aes = F)+
  geom_point(data=data_raw,aes(x=date,y=valueTrue),col="black",inherit.aes = F)+
  theme(text = element_text(size = text_size))+
  ggtitle(paste("Ingarch Timeseries",sep=" "),subtitle = paste("Fridge ID:",FID,",base window length:",frame,",Zero handling",zero_handling_ingarch,sep=" "))

if(save_plots){
  ggsave(filename = here("Plots",paste("ts_ing_id_",FID,"_win_lgth",frame,"_zero_handling_",zero_handling_ingarch,".png",sep="")),plot=p,height = 15,width = 20)
}

```