---
title: "Method comparision"
author: "Alexander Schwaiger"
date: "2023-01-20"
output: pdf_document
---
```{r eval=FALSE, message=FALSE, warning=FALSE}
source("General_Dependency.R")
source("Coda_Function.R") 
source("CountModel_Function.R")
source("General_Function.R")
source("General_PlotFunctions.R")
```

Preparation
```{r eval = FALSE}

#Choosing only fridges with all 4 categories
help1 <- weekly_category_data%>%
  group_by(fridge_id)%>%
  dplyr::select(main_category_id)%>%
  unique()%>%
  count(fridge_id)
  
ids_all <- help1$fridge_id[help1$n ==4]

ids <- ids_all

if(all(ids == ids_all)){
  ids_save <- "_all_"
}else {
  ids_save <- paste(ids,collapse = "-")
}

frame <- 0.5
window_method <- "extending"
save_results <- F
HistoryLength <- 1

#Ingarch specifications
MainCat <- 2

#Coda specifications

```


Performing the Analysis
```{r eval=FALSE, include=FALSE}
coda_result <-
  Coda.Analysis(
    Data_Raw  = weekly_category_data,
    Id = 4,
    Frame = 0.5,
    OneVsAll = T,
    PivotGroup =  NULL,
    Category_Main = c("1","2","3","4"),
    TSpace = F,
    Log = T,
    ZeroHandling = "simple",
    WindowMethod = "extending",
    TakeSubCategory= F,
    HistoryLength = 1,
    DL = 0.1
  )

if(save_results){
  save(coda_result,file=here("Code/results",paste("coda_result_ids",paste(ids_save,collapse="-"),"frame07",".RData",sep="")))
}


ingarch_result <-
  CountModel.Analysis(
    Data_Raw= weekly_category_data,
    Id = 4,
    Frame = 0.5,
    Distribution = "poisson",
    Category_Main = c("1","2","3","4"),
    WindowMethod = "extending",
    ZeroHandling = "none",
    External = F,
    Multicore = T,
    NCores = 4,
    PastOb = 1,
    PastMean = 1,
    HistoryLength = 1,
    TakeSubCategory = F,
    ModelType = "ingarch"
  )
  
  if(T){
  save(ingarch_result,file=here("Code/results",paste("ingarch_result_ids",paste(ids_save,collapse="-"),".RData",sep="")))

  }

```

Loading previous result
```{r}
ids <- unique(coda_result$result$id)
PredictionStep <- 1
frame <- unique(coda_result$result$frame)
window_method <- unique(coda_result$result$windowMethod)
save_results <- F
HistoryLength <- unique(coda_result$result$history)

#Ingarch specifications
distr<-unique(ingarch_result$result$distribution)
zero_handling_ingarch <- unique(ingarch_result$result$zeroHandling)
external <- unique(ingarch_result$result$external)
if(external){
  external_plot <-"with external factors"
}else external_plot <- ""
past_means <- unique(ingarch_result$result$pastMean)
past_obs <- unique(ingarch_result$result$pastOb)
ingarch_settings <- expand_grid(past_means,past_obs)
MainCat <- unique(ingarch_result$result$main_category)


#Coda specifications
#zero_handling_coda<-unique(coda_result$result$zero_handling)
tspace<-T
take_log<-T
one_vs_all<-T

if(!identical(ids,unique(ingarch_result$result$id)) || 
   frame != unique(ingarch_result$result$frame) ||
   window_method != unique(ingarch_result$result$windowMethod) ||
   HistoryLength != unique(ingarch_result$result$history)) {
  stop("Ingarch and Coda base specifications differ")
}
```


```{r}
#########BOTH METHODS############
#General 
Coda1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_best.RData")
Ingarch1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_.RData")
Inarclassic <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/inarclassic_result_ids_all_.RData")
Zim <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/zim_result_ids_all_.RData")
Count_Result <- rbind(Ingarch1$result,
                      Inarclassic$result,
                      Zim$result)

Codaspecial <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_dl01.RData")

Common_Names <- intersect(names(Ingarch1$result),names(coda_result$result))
CodaResult_Short <- Coda1$result %>% select(all_of(Common_Names))
CountModelResult_Short <- Count_Result %>% select(all_of(Common_Names))

AllResult <- rbind(CodaResult_Short,CountModelResult_Short)
#AllResult$window_baseLength[AllResult$window_baseLength==4]<-5

Plot.TimeseriesMultiple(weekly_category_data,AllResult,Id=c(4,24),File_Prefix= "Predictions")
Plot.TimeseriesCodaIngarchPI(weekly_category_data,CodaResult = Coda1,IngarchResult = Ingarch1,Id = c(4,24))
Plot.TimeseriesCodaIngarchPI(weekly_category_data,coda_result,Ingarch1,Id=24)
Plot.MethodComparision(AllResult,Category = c(3,4),ZIM=T,Split = F)

#History
Coda1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_best.RData")
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_history05.RData")

Ingarch1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_.RData")
Ingarch2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_history05.RData")

Coda_Combined <- rbind(Coda1$result,Coda2$result )
Ingarch_Combined <- rbind(Ingarch1$result,Ingarch2$result)

Plot.ErrorMeasureCombined(CodaCombined = Coda_Combined,IngarchCombined = Ingarch_Combined,Values=c("0.5","1"),Split=F,Variation = "history",LabelNames = c("0.5"="h=0.5","1"="h=1"))

#Frames
Coda1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_frame03.RData")
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_best.RData")
Coda3 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_frame07.RData")

Ingarch1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_frame03.RData")
Ingarch2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_.RData")
Ingarch3 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_frame07.RData")

Coda_Combined <- rbind(Coda1$result,
                       Coda2$result
                       ,Coda3$result
                       )
Ingarch_Combined <- rbind(Ingarch1$result,
                          Ingarch2$result
                          ,Ingarch3$result
                          )

Plot.ErrorMeasureCombined(CodaCombined = Coda_Combined,IngarchCombined = Ingarch_Combined,Values=c("0.3","0.5","0.7"),Split=F,Variation = "frame",LabelNames = c("0.3"="w=0.3","0.5"="w=0.5","0.7"="w=0.7"))

#Window Method
Coda1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_best.RData")
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_fixed.RData")

Ingarch1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_.RData")
Ingarch2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_fixed.RData")

Coda_Combined <- rbind(Coda1$result,Coda2$result )
Ingarch_Combined <- rbind(Ingarch1$result,Ingarch2$result)

Plot.ErrorMeasureCombined(CodaCombined = Coda_Combined,IngarchCombined = Ingarch_Combined,Values=c("fixed","extending"),Split=F,Variation = "windowMethod",LabelNames = c("fixed"="Fixed","extending"="Extending"))



########ONE METHOD##############
#####INGARCH######
#Distribution
Ingarch2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all__nbinom.RData")
Result_Combined <- rbind(Ingarch1$result,Ingarch2$result)
Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("Distribution"="distribution"),LabelNames=c("Poisson","Negativ Binomial"),Split=F,Category = c(1,2,3,4),Values = c("poisson","nbinom"))

#Past Mean
Ingarch2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_pm2.RData")
Result_Combined <- rbind(Ingarch1$result,Ingarch2$result)
Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("Past Means"="pastMean"),LabelNames=c("1","2"),Split=F,Category = c(1,2,3,4),Values = c("1","2"))

#Past Observations
Ingarch2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/ingarch_result_ids_all_po2.RData")
Result_Combined <- rbind(Ingarch1$result,Ingarch2$result)
Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("Past Observations"="pastOb"),LabelNames=c("1","2"),Split=F,Category = c(1,2,3,4),Values = c("1","2"))



#####CODA#####
Coda1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_best.RData")

#DL
Coda1 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_dl05.RData")
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_dl01.RData")
Coda3 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_dl001.RData")

Result_Combined <- rbind(Coda1$result,Coda2$result,Coda3$result)

Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("Delta"="dL"),LabelNames=c("0.1"="Delta=0.1","0.5"="Delta=0.5","0.01"="Delta=0.01"),Split=F,Category = c(4),Values = c(0.01,0.1,0.5),File_Post= "cat4")

Plot.TimeseriesSingle(weekly_category_data,Result_Combined,Id=c(100402,100403,100191),Variation=c("Delta"="dL"),LabelNames=c("0.1"="Delta=0.1","0.5"="Delta=0.5","0.01"="Delta=0.01"),Values = c(0.01,0.1,0.5),Title = "Coda",MyShapes = c(18,17,15),MyColour = c("darkgreen","darkorange","darkblue"))

#Zero Handling
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_all_values.RData")
Result_Combined <- rbind(Coda1$result,Coda2$result)
Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("Zero handling"="zeroHandling"),LabelNames=c("All","Simple Replacement"),Split=F,Category = c(1,2,3,4),Values = c("all","simple"),MyShapes = c(18,17),MyColour = c("darkgreen","darkorange"))

#TSpaces
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_tspace.RData")
Result_Combined <- rbind(Coda1$result,Coda2$result)

Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("T-Space"="tSpace"),LabelNames=c("TRUE"="T-Space","FALSE"="No T-Space"),Split=F,Category = c(1,2,3,4),Values = c(TRUE,FALSE),MyShapes = c(18,17),MyColour = c("darkgreen","darkorange"))

Plot.TimeseriesSingle(weekly_category_data,Result_Combined,Id=15,Save=T,SubCategory=F,Variation=c("T-Space"="tSpace"),LabelNames=c("TRUE"="T-Space","FALSE"="No T-Space"),Values = c(TRUE,FALSE),Title = "Coda")

#OneVsAll
Coda2 <- Object.Load("F:/Uni/Masterarbeit/Master-Thesis_git/Simulation/Code/results/coda_result_ids_all_no_ova.RData")
Result_Combined <- rbind(select(Coda1$result,-pivotGroup),Coda2$result)
Plot.ErrorMeasureSingle(ResultCombined=Result_Combined,Variation=c("One-vs-All"="oneVsAll"),LabelNames=c("TRUE"="Used","FALSE"="Not Used"),Split=F,Category = c(1,2,3,4),Values = c(TRUE,FALSE),MyShapes = c(18,17),MyColour = c("darkgreen","darkorange"))
```
