---
title: "coda_analysis_script"
author: "Alexander Schwaiger"
date: "2022-12-08"
output: pdf_document
---
```{r}
#source("dependencies.R")
#source("coda_functions.R")
```


```{r}
id<-12
zero_handling<-"zeros_only"
tspace<-T
prediction_error_step<-1
take_log<-T


```

Plot naming function

```{r}
coda.plot.name<-function(id,zero_handling,tspace,take_log){
  if(tspace){
    tspace_char<-"_tspace"
    
     if(take_log){
    take_log_char<-"_log"
  } else{
    take_log_char<-""
  }
    
  } else{
    tspace_char<-""
    take_log_char<-""
  }
  
  name<-paste("fridge_","id",id,"_zero_handling_",zero_handling,take_log_char,tspace_char,sep="")
  return(name)
}
```


Choosing and filtering relevant data
```{r}
data_raw<-weekly_category_data%>%
      filter(fridge_id==id)%>%
      dplyr::select(week_date,main_category_id,sold)%>%
                arrange(week_date)
```

Transforming data
```{r}
data_prepared<-coda.data.preperation(data_raw,zero_handling =zero_handling,tspace = tspace,log=take_log)%>%
                arrange(week_date)
data_length<-dim(data_prepared)[1]
```

Splitting in test and training data
```{r}
data_prepared_train<-data_prepared[c(1:floor(data_length/3)),]
data_prepared_test<-data_prepared[c((floor(data_length/3)+1):data_length),]

data_length_train<-dim(data_prepared_train)[1]
      
timeframes<-floor(c(0.3*data_length_train,0.5*data_length_train,0.9*data_length_train))
```

Calculating optimal parameters
```{r}
optimal_parameters<-coda.tuning(data_prepared_train,timeframes = timeframes,
                                                lag.max = 6,information_criteria_lag  ="AIC",
                                information_criteria_frame="prediction.error",prediction_error_step = 1,multicore = FALSE)
```


Non-transformed data
```{r}
data_prepared_notransf<-coda.data.preperation(data_raw,zero_handling="none",tspace=T)

data_notransf_test_windows<-windows(data_prepared_notransf[c((floor(data_length/3)+1):data_length),],
                                     optimal_parameters$frame,method = "overlapping",
                                     prediction_error_step = prediction_error_step)
      
```

Test windows for prepared data
```{r}
data_prepared_windows_test<-windows(data_prepared_test,optimal_parameters$frame,method = "overlapping",
                       prediction_error_step = prediction_error_step)
```

```{r}
prediction_results<-bind_rows(lapply(c(1:length(data_prepared_windows_test)),function(index){

        fitting_data<-data_prepared_windows_test[[index]]$fitting[,-1]
        true_value<-data_prepared_windows_test[[index]]$prediction_value[,-1]
        prediction_date<-data_prepared_windows_test[[index]]$prediction_value[1,1]
        
        model<-VAR(fitting_data,p=optimal_parameters$p)
        
        predicted_value<-predict(model,fitting_data,n.ahead = prediction_error_step)
        
        if(sum(is.na(predicted_value$fcst))>0){
          
          predicted_value<-NA
          } else {
          size<-length(true_value)
          
          
          predicted_values_vector<-matrix(data=NA,nrow=1,ncol=size)
          
          for(i in 1: size){
            
            predicted_values_vector[1,i]<-predicted_value$fcst[[i]][prediction_error_step]
            
          }
        }
                         
          
          tsums<-median(data_prepared_notransf$tsum,na.rm=TRUE)

        
        
        if(tspace){
          
                     predicted_value<-predicted_values_vector[-size]%>%matrix(nrow=1)%>%pivotCoordInv()
          predicted_value<-predicted_value*tsums
          
          if(take_log){
            
          predicted_value<-(append(predicted_value,exp(predicted_values_vector[size])))
            
          }
          else{

          predicted_value<-(append(predicted_value,predicted_values_vector[size])) 
          }
          
          true_value<-as.numeric(data_notransf_test_windows[[index]]$prediction_value[,-1])
            
          category<-factor(c("1","2","3","4","tsum"))
          
          if(index==1){
            naive_predicted_value<-apply(data_prepared_notransf[,-1],2,median,na.rm=TRUE)
          }else{
            naive_predicted_value<-as.numeric(tail(data_notransf_test_windows[[index]]$fitting[,-1],1))
            }
          
        }else{
          
          predicted_value<-predicted_values_vector%>%matrix(nrow=1)%>%pivotCoordInv()
          predicted_value<-predicted_value*tsums
          
          true_value<-as.numeric(data_notransf_test_windows[[index]]$prediction_value[,-c(1,6)])
          
          category<-factor(c("1","2","3","4"))
          
          if(index==1){
            naive_predicted_value<-apply(data_prepared_notransf[,-c(1,6)],2,median,na.rm=TRUE)
          }else{
            naive_predicted_value<-as.numeric(tail(data_notransf_test_windows[[index]]$fitting[,-c(1,6)],1))
            }
            
        }
        
        
        
        predicted_value<-round(as.numeric(predicted_value))

        prediction_error<-as.numeric(true_value-predicted_value)
        prediction_error_naive<-as.numeric(true_value-naive_predicted_value)
        
        
                  return(data.frame(prediction_error=prediction_error,
                            prediction_error_naive=prediction_error_naive,
                                  predicted_value=predicted_value,
                          true_value=true_value,
                          naive_predicted_value=naive_predicted_value,
                           category=category,
                         prediction_date=prediction_date)
                  )
        }))
```



Plotting results

```{r}
#View(prediction_results)
plot_data<-prediction_results%>%
  dplyr::select(predicted_value:prediction_date)%>%
  pivot_longer(cols=predicted_value:naive_predicted_value,
               names_to="type",values_to = "prediction_values")
```

```{r}
my_color <- setNames(c("red", "aquamarine", "black"),
                     c('predicted_value', 'naive_predicted_value', 'true_value'))

plot_name<-coda.plot.name(id=id,zero_handling = zero_handling,tspace=tspace,take_log = take_log)

p1<-ggplot(plot_data,aes(x=prediction_date,y=prediction_values,col=type))+
  facet_wrap(vars(category),nrow=length(unique(plot_data$category)),scales = "free")+
  geom_point(size=4)+
  geom_line(data=plot_data,
            aes(x=prediction_date,y=prediction_values,col=type))+
  scale_color_manual("Legend", values = my_color)+
  ggtitle("Actual Timeseries vs. predicted ",subtitle = paste("Fridge ID:",id,",zero handling:",zero_handling,sep=" "))

p1

ggsave(filename = paste("timeseries_",plot_name,".png",sep=""),plot=p1,height = 15,width = 20)
```



```{r}
p2<-ggplot(prediction_results,aes(x=prediction_date,y=prediction_error))+
  facet_wrap(vars(category),nrow=length(unique(prediction_results$category)),scales = "free")+
  geom_point(color="red",size=4)+
  geom_point(inherit.aes = FALSE,aes(x=prediction_date,y=prediction_error_naive),color="aquamarine",size=4)+
  geom_hline(yintercept = 0)+
  ggtitle("Prediction Error")

p2

ggsave(filename = paste("prediction_error_",plot_name,".png",sep=""),plot=p2,height = 15,width = 20)
```

```{r}
hist(sort(prediction_results$prediction_error,decreasing=TRUE)[-c(1:3)],
     xlab="errors",
     main="Histogram of 1-step ahead prediction errors")


png(paste("histogram_prediction_error_",plot_name,".png",sep=""),height = 15,width = 20,units = "cm",res=300)
hist(sort(prediction_results$prediction_error,decreasing=TRUE)[-c(1:3)],
     xlab="errors",
     main="Histogram of 1-step ahead prediction errors")
dev.off()
```

```{r}
qqnorm(sort(prediction_results$prediction_error,decreasing=TRUE))
qqnorm(sort(prediction_results$prediction_error,decreasing=TRUE)[-c(1:3)])

png(paste("qqplot_prediction_error_",plot_name,".png",sep=""),height = 15,width = 20,units = "cm",res=300)
qqnorm(sort(prediction_results$prediction_error,decreasing=TRUE))
dev.off()

```
```{r}
plot_data2<-prediction_results%>%
  dplyr::select(-(predicted_value:naive_predicted_value))%>%
  pivot_longer(cols=prediction_error:prediction_error_naive,
               names_to="type",values_to = "prediction_error")

plot_data2$type<-as.factor(plot_data2$type)
levels(plot_data2$type)<-c("VAR_model","naive_method")
```


```{r}
p3<-ggplot(plot_data2,aes(x=type,y=prediction_error))+
  facet_wrap(vars(category),ncol=length(unique(plot_data2$category)),scales = "fixed")+
  geom_boxplot()+
  ggtitle("Prediction error per method and category")
  
ggsave(filename = paste("box_prediction_error_",plot_name,".png",sep=""),plot=p3,height = 15,width = 20)
```






