---
title: "loglin_analysis_script"
author: "Alexander Schwaiger"
date: "2022-12-20"
output: pdf_document
---
Preparation
```{r}
id<-12
frame<-10

distr<-"nbinom"
```

```{r}
data_raw<-weekly_category_data%>%
      filter(fridge_id==id)%>%
      dplyr::select(week_date,main_category_id,sold)%>%
                arrange(week_date)%>%
    group_by(main_category_id,week_date)%>%
    dplyr::mutate(sold=sum(sold))%>%
    dplyr::distinct()%>%
    pivot_wider(names_from 
                = main_category_id,values_from = sold)%>%ungroup()

```


Timeseries for each group

```{r}
test_data_group1<-data_raw%>%dplyr::select(c("week_date","1"))%>%na.omit()

test_data_group2<-data_raw%>%dplyr::select(c("week_date","2"))%>%na.omit()

test_data_group3<-data_raw%>%dplyr::select(c("week_date","3"))%>%na.omit()
   
test_data_group4<-data_raw%>%dplyr::select(c("week_date","4"))%>%na.omit()
      
```


Model for each group

```{r}
test_data_windows_group1<-windows(test_data_group1,frame = frame,"overlapping",prediction_error_step = 1)
test_data_windows_group2<-windows(test_data_group2,frame = frame,"overlapping",prediction_error_step = 1)
test_data_windows_group3<-windows(test_data_group3,frame = frame,"overlapping",prediction_error_step = 1)
test_data_windows_group4<-windows(test_data_group4,frame = frame,"overlapping",prediction_error_step = 1)
```


```{r warning=FALSE}

par(mfrow=c(2,2))

prediction_results<-bind_rows(lapply(c(1:4),function(group_index){
  
  data<-data_raw%>%dplyr::select(c("week_date",paste(group_index)))%>%na.omit()
  
  data_window<-windows(data,frame = frame,"overlapping",prediction_error_step = 1)
  
  number_of_windows<-length(data_window)
  
  predicted_values<-bind_rows(lapply(c(1:number_of_windows),function(window_index){
    
    fitting_values<-data_window[[window_index]]$fitting
    true_value<-data_window[[window_index]]$prediction_value[[2]]
    
    model<-tsglm(fitting_values[[2]],model = list("past_obs"=1,"past_mean"=2),link="log",distr = distr)
    
    predicted_value<-predict(model,n.ahead=1)$pred
    
    return(data.frame(week_date=data_window[[window_index]]$prediction_value[[1]],
                      true_value=true_value,
                      predicted_value=predicted_value,
                      group=group_index))
    
  }))
  
  
  return(predicted_values)
  
}))
```


Plotting
```{r}
plot_data<-prediction_results%>%
  #dplyr::select(true_value:predicted_value)%>%
  pivot_longer(cols=true_value:predicted_value,
               names_to="type",values_to = "prediction_values")
```

```{r}
my_color <- setNames(c("red", "aquamarine", "black"),
                     c('predicted_value', 'naive_predicted_value', 'true_value'))


p1<-ggplot(plot_data,aes(x=week_date,y=prediction_values,col=type))+
  facet_wrap(vars(group),nrow=length(unique(plot_data$group)),scales = "free")+
  geom_point(size=1)+
  geom_line(data=plot_data,
            aes(x=week_date,y=prediction_values,col=type))+
  scale_color_manual("Legend", values = my_color)+
  ggtitle("Actual Timeseries vs. predicted ",subtitle = paste("Fridge ID:",id,sep=" "))+ 
  theme(text = element_text(size = 20))  

p1

ggsave(filename = paste("timeseries_loglin_",distr,"_id_",id,".png",sep=""),plot=p1,height = 15,width = 20)
```